## -*- encoding: utf-8 -*-


# This file was *autogenerated* from the file Calculus01.sagetex.sage
from sage.all_cmdline import *   # import sage library

## This file (Calculus01.sagetex.sage) was *autogenerated* from Calculus01.tex with sagetex.sty version 2021/10/16 v3.6.
import sagetex
_st_ = sagetex.SageTeXProcessor('Calculus01', version='2021/10/16 v3.6', version_check=True)
_st_.endofdoc()

